plugins {
  id 'java'
  id "application"
}

version = "1.0.0"

repositories {
  mavenCentral()

  maven {
    url "https://packages.confluent.io/maven"
  }
}

dependencies {
  implementation group: 'org.slf4j', name: 'slf4j-nop', version: '1.7.36'
  implementation group: 'org.apache.kafka', name: 'kafka-clients', version: '4.0.0'

  implementation group: 'io.confluent', name: 'kafka-client-plugins', version: '8.1.1-ce'
}

ext {
  javaMainClass = "example.ClientExample"
}

application {
  mainClass.set(javaMainClass)

  applicationDefaultJvmArgs = [
    "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=https://login.microsoftonline.com/1b9dca15-4db4-4905-8725-d318d11c6875/oauth2/v2.0/token"
  ]
}

jar {
  manifest {
    attributes "Main-Class": javaMainClass
  }
}
